# the name of the workflow
name: Upload Website to s3

on:
  push:
    branches: "master"
  pull_request:
    branches: "master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: create env file
        run: |
          touch .env
          echo REACT_APP_API_URL =${{ secrets.REACT_APP_API_URL }} >> .env
          echo REACT_APP_API_KEY =${{ secrets.REACT_APP_API_KEY }} >> .env
          echo REACT_APP_GOOGLE_CLIENT_ID =${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }} >> .env
          echo REACT_APP_WITH_RECORDS =${{ secrets.REACT_APP_WITH_RECORDS }} >> .env
          echo REACT_APP_RECORD_URL =${{ secrets.REACT_APP_RECORD_URL }} >> .env
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run lint and prettier
        run: npm run validate

      - name: Build
        run: npm run build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_WITH_RECORDS: ${{ secrets.REACT_APP_WITH_RECORDS }}
          REACT_APP_RECORD_URL: ${{ secrets.REACT_APP_RECORD_URL }}
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # optional: defaults to us-east-1
          SOURCE_DIR: "build" # optional: defaults to entire repository
